version: "3.8"

services:
  my_force_nginx:
    container_name: my_force_nginx
    image: nginx:stable-alpine
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      - "8081:81"
    depends_on:
      - my_force_php_fpm
    restart: unless-stopped

  my_force_php_fpm:
    container_name: my_force_php_fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
    - ./:/app
    depends_on:
      - my_force_php_cli
    restart: unless-stopped

  my_force_php_cli:
    container_name: my_force_php_cli
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - my_force_postgres

  my_force_postgres:
    container_name: my_force_postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  default:
    external: true
    name: my_force_network

volumes:
  postgres-db-data: